hell_yeah/config/routes.rb
HellYeah::Application.routes.draw do
  root :to => 'statements#index'
  
  resources :statements do
    resources :votes, :only => [:new]
  end
  
  match '/auth/:provider/callback', :to => 'votes#create'
end

hell_yeah/app/models/statement.rb
class Statement < ActiveRecord::Base
  has_many :votes
  has_many :users, :through => :votes

  validates_presence_of :text
  validates_uniqueness_of :text
end

hell_yeah/app/models/user.rb
class User < ActiveRecord::Base
  has_many :votes
  has_many :statements, :through => :votes

  validates_uniqueness_of :screen_name

  def self.from_auth(auth)
    existing = User.find_by_screen_name(auth['user_info']['nickname'])
    existing || User.create(:name => auth['user_info']['name'], :screen_name => auth['user_info']['nickname'])
  end
end

hell_yeah/app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :user
  belongs_to :statement

  validates_uniqueness_of :user_id, :scope => :statement_id
end

hell_yeah/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

hell_yeah/app/controllers/statements_controller.rb
class StatementsController < ApplicationController
  # GET /statements
  # GET /statements.xml
  def index
    @statements = Statement.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @statements }
    end
  end

  # GET /statements/1
  # GET /statements/1.xml
  def show
    @statement = Statement.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @statement }
    end
  end

  # GET /statements/new
  # GET /statements/new.xml
  def new
    @statement = Statement.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @statement }
    end
  end

  # GET /statements/1/edit
  def edit
    @statement = Statement.find(params[:id])
  end

  # POST /statements
  # POST /statements.xml
  def create
    @statement = Statement.new(params[:statement])

    respond_to do |format|
      if @statement.save
        format.html { redirect_to(statements_path, :notice => 'Statement was successfully created.') }
        format.xml  { render :xml => @statement, :status => :created, :location => @statement }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @statement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /statements/1
  # PUT /statements/1.xml
  def update
    @statement = Statement.find(params[:id])

    respond_to do |format|
      if @statement.update_attributes(params[:statement])
        format.html { redirect_to(@statement, :notice => 'Statement was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @statement.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /statements/1
  # DELETE /statements/1.xml
  def destroy
    @statement = Statement.find(params[:id])
    @statement.destroy

    respond_to do |format|
      format.html { redirect_to(statements_url) }
      format.xml  { head :ok }
    end
  end
end

hell_yeah/app/controllers/votes_controller.rb
class VotesController < ApplicationController
  protect_from_forgery :except => :create

  def new
    session[:last_statement_id] = params[:statement_id]
    redirect_to '/auth/twitter'
  end

  def create
    redirect_to('/', :alert => 'No statement was selected to vote for.') and return unless session[:last_statement_id]
    @user = User.from_auth(auth)
    @statement = Statement.find_by_id(session.delete(:last_statement_id))
    @vote = Vote.new(:user => @user, :statement => @statement)

    if @vote.save
      redirect_to statements_path, :notice => "Your vote for '#{@statement.text}' has been recorded."
    else
      redirect_to statements_path, :alert => "Couldn't save the vote...did you already vote for this one?"
    end
  end

  protected

  def auth
    env['omniauth.auth']
  end
end

hell_yeah/app/helpers/application_helper.rb
module ApplicationHelper
end

hell_yeah/app/helpers/statements_helper.rb
module StatementsHelper
end

hell_yeah/app/helpers/votes_helper.rb
module VotesHelper
end

hell_yeah/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HellYeah!</title>
  <%= stylesheet_link_tag 'application' %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>
  <div id='wrapper'>
    <header>
      <h1><a href='/'><em>Hell</em>Yeah!</a></h1>
    </header>
    <%= yield %>
    <footer>Demo app for <b>OmniAuth: From the Ground Up</b>. &copy; Michael Bleigh, no rights reserved.</footer>
  </div>
</body>
</html>

hell_yeah/app/views/statements/_form.html.erb
<%= form_for(@statement) do |f| %>
  <% if @statement.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@statement.errors.count, "error") %> prohibited this statement from being saved:</h2>

      <ul>
      <% @statement.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :text %><br />
    <%= f.text_field :text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

hell_yeah/app/views/statements/_statement.html.erb
<section class='statement'>
  <h1><%= statement.text %></h1>
  <ul class='voters'>
    <% for voter in statement.users %>
      <li><%= link_to image_tag("http://tweetimag.es/i/#{voter.screen_name}_m"), "http://twitter.com/#{voter.screen_name}", :target => '_blank' %>
    <% end %>
  </ul>
  <%= link_to "Hell Yeah!", new_statement_vote_path(statement) %>
</section>

hell_yeah/app/views/statements/edit.html.erb
<h1>Editing statement</h1>

<%= render 'form' %>

<%= link_to 'Show', @statement %> |
<%= link_to 'Back', statements_path %>

hell_yeah/app/views/statements/index.html.erb
<p class='flash' id='notice'><%= notice %></p>
<p class='flash' id='alert'><%= alert %></p>

<%= render @statements %>

<%= link_to 'New Statement', new_statement_path %>

hell_yeah/app/views/statements/new.html.erb
<h1>New statement</h1>

<%= render 'form' %>

<%= link_to 'Back', statements_path %>

hell_yeah/app/views/statements/show.html.erb
<p id="notice"><%= notice %></p>
<p id="alert"><%= alert %></p>

<%= render @statement %>

<%= link_to 'Edit', edit_statement_path(@statement) %> |
<%= link_to 'Back', statements_path %>